# Exports
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=~/.venvs
export PYTHONDONTWRITEBYTECODE=1
export GOPATH=$HOME/go
export EDITOR=vim

# Load nvm if present
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

ZSH_THEME="thrawny"

plugins=(
  git
  github
  history
  history-substring-search
  docker
  python
  zsh-autosuggestions
  jira
  web-search
)

PATH=$PATH:$GOPATH/bin:$HOME/dotfiles/bin
[[ ":$PATH:" != *":/usr/local/bin:"* ]] && PATH="/usr/local/bin:${PATH}"
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && PATH="$HOME/.local/bin:${PATH}"

export PATH

# OSX specific stuff
if [[ "$(uname)" == "Darwin" ]]; then
  export LANG="C"
  plugins+=(osx)
else
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi;

source $ZSH/oh-my-zsh.sh

unalias -m "gpo"
unalias -m "gp"

# Aliases
alias pi="pip install -r requirements.txt"
alias pc="pip-compile"
alias fig="docker-compose"
alias svh="sudo vim /etc/hosts"
alias vbm="VBoxManage"
alias pycheck='isort && flake8 && pytest'
alias pyupdatecheck='pip-compile --upgrade --dry-run | diff -i requirements.txt -'
alias vpn='sudo openvpn'
alias kc='kubectl'
alias kt='stern'
alias kca='kubectl apply -f'
alias kcn='kubectl -n kube-system'
alias kcp='kubectl get pods'
alias gsha='git rev-parse HEAD | cut -c1-9'
alias kclf='kubectl logs -f'
alias kcl='kubectl logs'
alias kcu='kubectl config use-context'
alias hb='hub browse'
alias gt='gofmt -w . && golangci-lint run --skip-files lab.go && go test ./...'
alias b='bat -p --pager=never'
alias tilt='KUBECONFIG=~/.kube/docker-for-desktop tilt'
alias kubectl-extract-context='kc config view --minify=true --flatten --context'
alias kec='kubectl-extract-context'
alias ci='openci'
alias vkcp='watch -n 1 kubectl get pods'
alias kvcp='watch -n 1 kubectl get pods'
alias v='watch -n 1'

function gtrm() {
  git tag --delete $1 && git push --delete origin $1
}

# Functions
function gpo() {
  git push -u origin $(git_current_branch)
}

function gp() {
  git push --force-with-lease
}

function kcaev() {
  envsubst < $1 | kubectl apply -f -
}

function projname() {
  basename $(git rev-parse --show-toplevel)
}

function github_org() {
  git config --get remote.origin.url | ggrep -oP '.*:\K(.*)(?=/.*)'
}

function pr() {
  open "https://github.com/$(github_org)/$(projname)/pull/new/$(git_current_branch)"
}

function ktc() {
  stern $1 -c $1 -e "kube-probe|Checking status..."
}

function sd() {
  stage=${1:-"production"}
  ref=${2:-$(git_current_branch)}
  open "${SAMSON_URL}/projects/$(projname)/stages/${stage}/deploys/new?reference=${ref}"
}


# function cpr() {
#   open "$(hub pull-request -m $(git_current_branch))"
# }


# Autocomplete
# source <(kubectl completion zsh)
# source <(helm completion zsh)
source <(helm completion zsh | sed -E 's/\["(.+)"\]/\[\1\]/g')  # Fixed in v2.13.3
source <(kops completion zsh)
source <(kubesec completion zsh)



[ -f ~/.zsh.local ] && source ~/.zsh.local
