# Exports
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=~/.venvs
export PYTHONDONTWRITEBYTECODE=1

# Load nvm if present
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

ZSH_THEME="thrawny"

plugins=(git github history history-substring-search docker pip python zsh-autosuggestions)

[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && PATH="$HOME/.local/bin:${PATH}"

# OSX specific stuff
if [[ "$(uname)" == "Darwin" ]]; then
  # export PATH=$HOME/bin:/usr/local/bin:$PATH
  plugins+=(osx)
else
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi;

source $ZSH/oh-my-zsh.sh

unalias -m "gpo"
unalias -m "gp"

# Aliases
alias pi="pip install -r requirements.txt"
alias pc="pip-compile"
alias fig="docker-compose"
alias svh="sudo vim /etc/hosts"
alias vbm="VBoxManage"
alias pycheck='isort && flake8 && pytest'
alias pyupdatecheck='pip-compile --upgrade --dry-run | diff -i requirements.txt -'
alias vpn='sudo openvpn'
alias kc='kubectl'
alias kt='stern'
alias kca='kubectl apply -f'
alias kcn='kubectl -n kube-system'
alias kcp='kubectl get pods'
alias gsha='git rev-parse HEAD | cut -c1-9'
alias kcl='kubectl logs -f'
alias kcu='kubectl config use-context'
alias hb='hub browse'
alias gt='go test ./...'

# Functions
function gpo() {
  git push -u origin $(git_current_branch)
}

function gp() {
  git push --force-with-lease
}

function kcaev() {
  envsubst < $1 | kubectl apply -f -
}

function projname() {
  basename $(git rev-parse --show-toplevel)
}

function pr() {
  open "https://github.com/${GITHUB_ORG}/$(projname)/pull/new/$(git_current_branch)"
}

function ci() {
  open "https://app.wercker.com/${GITHUB_ORG}/$(projname)/runs"
}

# function cpr() {
#   open "$(hub pull-request -m $(git_current_branch))"
# }


# Autocomplete
# source <(kubectl completion zsh)
source <(helm completion zsh)
source <(kops completion zsh)


[ -f ~/.zsh.local ] && source ~/.zsh.local
