# Exports
export ZSH=$HOME/.oh-my-zsh
export WORKON_HOME=~/.venvs
export PYTHONDONTWRITEBYTECODE=1
export GOPATH=$HOME/go
export EDITOR=vim

# Load nvm if present
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

ZSH_THEME="thrawny"

plugins=(
  git
  github
  history
  history-substring-search
  docker
  python
  zsh-autosuggestions
  jira
  web-search
)

[[ ":$PATH:" != *":/usr/local/bin:"* ]] && PATH="/usr/local/bin:${PATH}"
PATH=$GOPATH/bin:$HOME/dotfiles/bin:$PATH
[[ ":$PATH:" != *":$HOME/.local/bin:"* ]] && PATH="$HOME/.local/bin:${PATH}"

export PATH

# OSX specific stuff
if [[ "$(uname)" == "Darwin" ]]; then
  export LANG="C"
  plugins+=(osx)
else
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
fi;

source $ZSH/oh-my-zsh.sh

bindkey ^F forward-word
bindkey ^f forward-word

unalias -m "gpo"
unalias -m "gp"
unalias -m "gcam"

# Aliases
alias pi="pip install -r requirements.txt"
alias pc="pip-compile"
alias fig="docker-compose"
alias svh="sudo vim /etc/hosts"
alias vbm="VBoxManage"
alias pycheck='isort && flake8 && pytest'
alias pyupdatecheck='pip-compile --upgrade --dry-run | diff -i requirements.txt -'
alias vpn='sudo openvpn'
alias kc='kubectl'
alias kt='stern'
alias kca='kubectl apply -f'
alias kcn='kubectl -n kube-system'
alias kci='kubectl -n istio-system'
alias kcp='kubectl get pods'
alias gsha='git rev-parse HEAD | cut -c1-9'
alias kclf='kubectl logs -f'
alias kcl='kubectl logs'
alias kcu='kubectl config use-context'
alias hb='hub browse'
alias gt='gofmt -w . && golangci-lint run --skip-files lab.go && go test ./...'
alias b='bat -p --pager=never'
alias tilt='KUBECONFIG=~/.kube/docker-for-desktop tilt'
alias kubectl-extract-context='kc config view --minify=true --flatten --context'
alias kec='kubectl-extract-context'
alias ci='openci'
alias vkcp='watch -n 1 kubectl get pods'
alias kvcp='watch -n 1 kubectl get pods'
alias v='watch -n 1'
alias kcd='kc drain --ignore-daemonsets --delete-local-data --force'
alias gcam="git add -A && git commit -m"
alias tfa='terraform apply'
alias bu='brew upgrade'
alias mp='microplane'

# Functions
function gtrm() {
  git tag --delete $1 && git push --delete origin $1
}

function gpo() {
  git push -u origin $(git_current_branch)
}

function gp() {
  git push --force-with-lease
}

function kcaev() {
  envsubst < $1 | kubectl apply -f -
}

function projname() {
  basename $(git rev-parse --show-toplevel)
}

function github_org() {
  git config --get remote.origin.url | ggrep -oP '.*:\K(.*)(?=/.*)'
}

function pr() {
  open "https://github.com/$(github_org)/$(projname)/pull/new/$(git_current_branch)"
}

function ktc() {
  stern $1 -c $1 -e "kube-probe|Checking status...|health check|Accepted connection from /100"
}

function kcpf() {
  while true; do
    kubectl port-forward "$@"
  done
}

function asudo() {
  export $(awsudo default)
}

function dbp() {
  docker build -t $1 . && docker push $1
}

function ktjq() {
  stern $1 --output raw | jq -r -R 'fromjson? | "\(.["@timestamp"]) [\(.level)] - \(.message)"'
}

function uuid() {
  python3 -c "import uuid;print(uuid.uuid4())"
}

. $HOME/.asdf/asdf.sh
. $HOME/.asdf/completions/asdf.bash

source <(kubectl completion zsh)
source <(helm completion zsh)
source <(kops completion zsh)
source <(kubesec completion zsh)
# source /usr/local/bin/aws_zsh_completer.sh

[ -f ~/.zsh.local ] && source ~/.zsh.local

eval "$(direnv hook zsh)"
