- name: symlinks for all are present
  file:
    state: link
    dest: "{{ home_dir }}/.{{ item.name }}"
    src: "{{ dotfiles_dir }}/{{ item.dir|default('') }}{{ item.name }}"
  with_items:
  - { "name": "vim" }
  - { "name": "zshrc", "dir": "shell/" }
  - { "name": "ideavimrc", "dir": "misc/" }
  - { "name": "gitconfig", "dir": "git/" }
  - { "name": "gitignoreglobal", "dir": "git/" }

- name: "custom zsh theme is symlinked to .oh-my-zsh/custom"
  file:
    state: link
    dest: "{{ home_dir }}/.oh-my-zsh/custom/{{ item }}"
    src: "{{ dotfiles_dir }}/misc/{{ item }}"
  with_items:
  - thrawny.zsh-theme

- name: ~/.local/bin directory is present
  file:
    path: "{{ home_dir }}/.local/bin"
    state: directory
    recurse: yes

- name: ~/.config/direnv is present
  file:
    path: "{{ home_dir }}/.config/direnv"
    state: directory

- name: direnvrc is symlinked to ~/.config/direnv/direnvrc
  file:
    state: link
    dest: "{{ home_dir }}/.config/direnv/direnvrc"
    src: "{{ dotfiles_dir }}/misc/direnvrc"

- name: ~/.config/ghostty is present
  file:
    path: "{{ home_dir }}/.config/ghostty"
    state: directory

- name: ghostty is symlinked to ~/.config/ghostty/config
  file:
    state: link
    dest: "{{ home_dir }}/.config/ghostty/config"
    src: "{{ dotfiles_dir }}/misc/ghostty-config"

- name: neovim config
  file:
    state: link
    dest: "{{ home_dir }}/.config/nvim"
    src: "{{ dotfiles_dir }}/nvim"

- name: default npm packages
  file:
    path: "{{ home_dir }}/.default-npm-packages"
    src: "{{ dotfiles_dir }}/misc/default-npm-packages"
    state: link

- name: ~/.claude directory is present
  file:
    path: "{{ home_dir }}/.claude"
    state: directory

- name: claude commands directory is symlinked
  file:
    state: link
    dest: "{{ home_dir }}/.claude/commands"
    src: "{{ dotfiles_dir }}/claude/commands"
