# vim:ft=ansible:

- hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME')}}"
    dotfiles_dir: "{{ home_dir }}/dotfiles"
  tasks:
    - include: all_config.yml
    - include: all_software.yml
    - include: ubuntu_software.yml
      when: ansible_distribution == 'Ubuntu'
    - include: ubuntu_config.yml
      when: ansible_distribution == 'Ubuntu'
    - include: osx_config.yml
      when: ansible_distribution == 'MacOSX'
    - include: osx_software.yml
      when: ansible_distribution == 'MacOSX'
    - include: vim.yml
    - include: fonts.yml
