# vim:ft=yaml.ansible:

- name: check if cursor is installed
  ansible.builtin.stat:
    path: "{{ home_dir }}/Library/Application Support/Cursor"
  register: cursor

- name: "cursor settings files are symlinked"
  file:
    state: link
    dest: "{{ home_dir }}/Library/Application Support/Cursor/User/{{ item }}"
    src: "{{ dotfiles_dir }}/cursor/{{ item }}"
  with_items:
  - settings.json
  - keybindings.json
  when: cursor.stat.isdir is defined and cursor.stat.isdir

- name: "osx setup has been run"
  ansible.builtin.script: "{{ dotfiles_dir }}/osx/setup.sh"

- name: ~/Screenshots folder is present
  file:
    path: "{{ home_dir }}/Screenshots"
    state: directory
    recurse: yes

- name: "aerospace.toml is symlinked"
  file:
    state: link
    dest: "{{ home_dir }}/.aerospace.toml"
    src: "{{ dotfiles_dir }}/aerospace/aerospace.toml"
