# vim:ft=ansible:

- name: virtualenvwrapper conf is added to .zsh.local
  lineinfile:
    dest: "{{ home_dir }}/.zsh.local"
    line:  "{{ item }}"
    state: present
    create: yes
  with_items:
    - "export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3"
    - "source /usr/local/bin/virtualenvwrapper.sh"
  when: ansible_distribution == 'MacOSX'

- name: symlinks for osx are present
  file:
    state: link
    dest: "{{ home_dir }}/.{{ item.name }}"
    src: "{{ dotfiles_dir }}/{{ item.dir|default('') }}{{ item.name }}"
  with_items:
    - {'name': 'tmux.conf', 'dir': 'shell/'}
  when: ansible_distribution == 'MacOSX'

- name: "vscode settings files are symlinked"
  file:
    state: link
    dest: "{{ home_dir }}/Library/Application Support/Code/User/{{ item }}"
    src: "{{ dotfiles_dir }}/vscode/{{ item }}"
  with_items:
    - settings.json
    - keybindings.json

- name: "launchagents are symlinked"
  file:
    state: link
    dest: "{{ home_dir }}/Library/LaunchAgents/{{ item }}"
    src: "{{ dotfiles_dir }}/osx/{{ item }}"
  with_items:
    - com.jle.brew-update.plist

- name: "launchagents are loaded"
  command: "launchctl load {{ item }}"
  with_items:
    - com.jle.brew-update.plist
