theme = Molokai
background = #1c1c1c
foreground = #f0f0f0
font-family = CaskaydiaMono Nerd Font
font-size = 14
font-thicken = true
font-thicken-strength = 50
window-padding-x = 10
window-padding-y = 2
gtk-titlebar = false
gtk-single-instance = true
confirm-close-surface = false
cursor-style-blink = false
font-synthetic-style = false
minimum-contrast = 1.2
selection-background = #49483e
selection-foreground = #f8f8f2
palette = 0=#5c5c5c
palette = 8=#808080
macos-option-as-alt = true
keybind = shift+enter=text:\\\n\r
