theme = {{ghostty.theme}}
background = {{ghostty.background}}
foreground = {{ghostty.foreground}}
font-family = CaskaydiaMono Nerd Font
font-size = 14
font-thicken = true
font-thicken-strength = 50
window-padding-x = 10
window-padding-y = 2
gtk-titlebar = false
gtk-single-instance = true
confirm-close-surface = false
cursor-style-blink = false
font-synthetic-style = false
minimum-contrast = 1.2
selection-background = {{ghostty.selectionBackground}}
selection-foreground = {{ghostty.selectionForeground}}
palette = 0={{ghostty.palette0}}
palette = 8={{ghostty.palette8}}
macos-option-as-alt = true
keybind = shift+enter=text:\\\n\r
