theme = {{ghostty.theme}}
background = {{ghostty.background}}
foreground = {{ghostty.foreground}}
font-family = CaskaydiaMono Nerd Font
font-size = 14
font-thicken = true
font-thicken-strength = 50
window-padding-x = 10
window-padding-y = 2
gtk-titlebar = false
gtk-single-instance = true
confirm-close-surface = false
cursor-style-blink = false
font-synthetic-style = false
minimum-contrast = 1.2
selection-background = {{ghostty.selectionBackground}}
selection-foreground = {{ghostty.selectionForeground}}
palette = 0={{ghostty.palette0}}
palette = 8={{ghostty.palette8}}
macos-option-as-alt = true
keybind = ctrl+shift+j=unbind
# Let Herdr handle agent selection and navigation.
keybind = super+1=unbind
keybind = super+2=unbind
keybind = super+3=unbind
keybind = super+4=unbind
keybind = super+5=unbind
keybind = super+6=unbind
keybind = super+7=unbind
keybind = super+8=unbind
keybind = super+9=unbind
keybind = super+k=unbind
keybind = shift+enter=text:\\\n\r
