# Starship prompt configuration (minimal, only non-defaults)

# Root prompt layout
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$env_var\
$kubernetes\
$docker_context\
$python\
$golang\
$nodejs\
$rust\
$terraform\
$cmd_duration\
$line_break\
$character"""

# Hide stashed symbol in Git status
[git_status]
stashed = ""

# Hide branch symbol (keep default style/format)
[git_branch]
symbol = ""

# Show duration for commands longer than 500ms
[cmd_duration]
min_time = 500

# Enable Kubernetes module; show context only (no namespace)
[kubernetes]
disabled = false
format = 'on [$symbol$context]($style) '

# Devpod indicator
[env_var.DEVPOD]
format = "in [📦 devpod]($style) "
style = "bold blue"
