# Walker configuration with Molokai theme
theme = "molokai"
theme_location = ["~/.config/walker/themes/"]

# Search settings
[search]
placeholder = " Type to search..."

# List configuration
[list]
max_entries = 200
cycle = true

# Application launcher settings
[builtins.applications]
placeholder = " Type to search..."
prioritize_new = false
context_aware = false

# Runner settings
[builtins.runner]
shell_config = ""

# Calculator settings
[builtins.calc]
name = "Calculator"
prefix = "="

# Emoji picker
[builtins.emojis]
name = "Emojis"
prefix = ":"

# File finder
[builtins.finder]
use_fd = true
prefix = "."