# Zinit - Modern Zsh Plugin Manager
- name: "Ensure Zinit parent directory exists"
  file:
    path: "{{ home_dir }}/.local/share/zinit"
    state: directory
    mode: '0755'

- name: "Zinit is installed"
  git:
    repo: "https://github.com/zdharma-continuum/zinit.git"
    dest: "{{ home_dir }}/.local/share/zinit/zinit.git"
    force: yes

- name: "zsh auto suggestions are present"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ home_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

# Tmux Plugin Manager
- name: "Ensure tmux plugins directory exists"
  file:
    path: "{{ home_dir }}/.tmux/plugins"
    state: directory
    mode: '0755'

- name: "tmux plugin manager is present"
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ home_dir }}/.tmux/plugins/tpm"

- name: "tmux plugins have been installed"
  command: "{{ home_dir }}/.tmux/plugins/tpm/bin/install_plugins"
  args:
    creates: "{{ home_dir }}/.tmux/plugins/tmux-yank"
