# vim:ft=yaml.ansible:

- name: powerline font repo is present
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ home_dir }}/Downloads/fonts"
  when: ansible_distribution == 'Ubuntu'

- name: ensure fonts are copied to /usr/share/fonts/opentype
  command: "cp -r {{ home_dir }}/Downloads/fonts/SourceCodePro /usr/share/fonts/opentype/"
  args:
    creates: /usr/share/fonts/opentype/SourceCodePro
  become: yes
  when: ansible_distribution == 'Ubuntu'
