extra_keywords = ["symlink", "cachix", "thrawny"]
[replacements]
wavois = "wayvoice"
nbin = "nvim"
n-bar = "env var"
"n var" = "env var"
".files" = "dotfiles"
simlink = "symlink"
"sim linking" = "symlinking"
lasergit = "lazygit"
"operational shock" = "operational soc"
prequel = "prequal"
czu = "csv"
pubview = "webview"
"guitar action" = "github action"
throney = "thrawny"
cashics = "cachix"
kasex = "Cachix"
